"""empty message

Revision ID: 10653fc9a5f6
Revises: 
Create Date: 2018-12-19 17:42:58.606416

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '10653fc9a5f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BHA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=True),
    sa.Column('case_file', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('create_by', sa.String(length=20), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('survey_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BHA_Component',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('bha_id', sa.Integer(), nullable=True),
                    sa.Column('bha_type', sa.String(length=20), nullable=True),
                    sa.Column('bit_size', sa.String(length=20), nullable=True),
                    sa.ForeignKeyConstraint(['bha_id'], ['BHA.id'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('BHA_Round',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('round', sa.String(length=50), nullable=True),
                    sa.Column('status', sa.String(length=20), nullable=True),
                    sa.Column('bha_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['bha_id'], ['BHA.id'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BHA_Round')
    op.drop_table('BHA_Component')
    op.drop_table('BHA')
    # ### end Alembic commands ###
