"""empty message

Revision ID: b1eca4d0bf03
Revises: 
Create Date: 2018-12-15 14:45:34.826620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1eca4d0bf03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BHA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=True),
    sa.Column('case_file', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('create_by', sa.String(length=20), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('survey_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BHA_Component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bha_id', sa.Integer(), nullable=True),
    sa.Column('bha_type', sa.String(length=20), nullable=True),
    sa.Column('bit_size', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['bha_id'], ['BHA.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BHA_Component')
    op.drop_table('BHA')
    # ### end Alembic commands ###
